version: '3.8'

services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smorty
    volumes:
      - ./pg_data:/var/lib/postgresql